
---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: demo-app
        api_version: v1
        kind: Namespace
        state: present
    - name: Deploy nginx app in the newly created namespace
      kubernetes.core.k8s:
        src: ../Module_11-EKS/nginx-config.yaml
        state: present
        namespace: demo-app