
pipeline {
    agent any

    tools {
        maven 'Maven' //the value must be the same as in the Web UI
    }

    environment {
        ANSIBLE_SERVER_ADDRESS = "18.195.35.242" // ubuntu distro
    }

    stages {
        stage("Copy all the necessary files to Ansible Control Node") {
            steps {
                script {
                    dir("Module_15-Configuration_management_with_Ansible") {
                        sshagent(credentials: ['ansible-connection']) {
                        sh "scp -o StrictHostKeyChecking=no ansible.cfg deploy-docker-from-jenkins.yaml inventory_aws_ec2.yaml ubuntu@${ANSIBLE_SERVER_ADDRESS}:/home/ubuntu"
                        withCredentials([sshUserPrivateKey(credentialsId: "managed-ec2", keyFileVariable: "keyfile", usernameVariable: "user")]) {
                                sh "scp $keyfile ubuntu@${ANSIBLE_SERVER_ADDRESS}:/home/ubuntu/ssh-key.pem"
                            }
                        }
                    }
                }
            }
        }
    }   
}