version: '3'
services:
  javaapp:
    image: "negru1andrei/java-maven-app:${IMAGE_TAG}"
    ports:
      - "8080:8080"
  postgres:
    image: "postgres:15"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
