def gv

pipeline {
    agent any

    tools {
        maven 'Maven' //the value must be the same as in the Web UI
    }

    stages {
        stage("init") {
            steps {
                script {
                    gv = load "Module_9-AWS/script.groovy"
                }
            }
        }
        stage("build java jar") {
            steps {
                script {
                    echo "building jar"
                    gv.buildJar()
                }
            }
        }
        stage("build docker image") {
            steps {
                script {
                    echo "building image"
                    gv.buildImage "2.2.7-11"
                }
            }
        }
        stage("deploy the image") {
            steps {
                script {
                    echo "deploying"
                    //gv.deployApp "2.2.7-11"
                    def dockerCmd = "docker run -d -p 8080:8080 2.2.7-11"
                    sshagent(credentials: ['ec2-key']) {
                        sh "ssh -o StrictHostKeyChecking=no ec2-user@18.194.140.242 2.2.7-11"
                    }
                }
            }
        }
    }   
}