def gv

pipeline {
    agent any

    tools {
        maven 'Maven' //the value must be the same as in the Web UI
    }

    environment {
        AWS_ACCESS_KEY_ID = credentials("aws_access_key_id")
        AWS_SECRET_ACCESS_KEY = credentials("aws_secret_access_key")
    }

    stages {
        stage("init") {
            steps {
                script {
                    gv = load "Module_12-Terraform/script.groovy"
                }
            }
        }
        stage("increment version") {
            steps {
                script {
                dir("./Module_8-CICD_with_Jenkins/java-maven-app-master/") { 
                sh 'mvn build-helper:parse-version versions:set \
                        -DnewVersion=\\\${parsedVersion.majorVersion}.\\\${parsedVersion.minorVersion}.\\\${parsedVersion.nextIncrementalVersion} \
                        versions:commit'
                def matcher = readFile('pom.xml') =~ '<version>(.+)</version>' //regex to match every line containing every version
                def version = matcher[0][1] //first line containing version > child (actual string with the version number)
                env.IMAGE_TAG = "$version-$BUILD_NUMBER"
                    }
                }  
            }
        }
        stage("build java jar") {
            steps {
                script {
                    echo "building jar"
                    gv.buildJar()
                }
            }
        }
        stage("build docker image") {
            steps {
                script {
                    echo "building image"
                    gv.buildImage "${env.IMAGE_TAG}"
                }
            }
        }
        stage("provision ec2 server") {
            environment {
                TF_VAR_env_prefix = "test"
            }
            steps {
                script {
                    dir("./Module_12-Terraform") {
                    echo "provision ec2 server"
                    sh("terraform init")
                    sh("terraform apply --auto-approve")
                    env.EC2_PUBLIC_IP = sh(script: "terraform output ec2_public_ip", returnStdout: true).trim()
                    echo "Public IP of the EC2: ${env.EC2_PUBLIC_IP}"
                    sleep(time: 210, unit: "SECONDS")
                    }
                }
            }
        }
        stage("deploy the image") {
            steps {
                script {
                    echo "deploying java and postgres"
                    echo "${env.IMAGE_TAG} and ${env.EC2_PUBLIC_IP}"
                    gv.deployAppWithDockerCompose("${env.IMAGE_TAG}", "${env.EC2_PUBLIC_IP}")
                }
            }
        }
        stage("commit version bump") {
            steps {
                    script {
                        withCredentials([string(credentialsId: 'github-access-token', variable: 'TOKEN')]) {
                        sh 'git config user.email "jenkins@example.com"'
                        sh 'git config user.name "jenkins"'
                        sh 'git remote set-url origin https://$TOKEN@github.com/ngrandrei/devops-bootcamp.git'
                        sh "git add ."
                        sh 'git commit -m "version bump to \\\${env.IMAGE_TAG}"'
                        
                        sh "git push origin HEAD:main"
                        }
                    }
            }
        }
    }   
}